language: java
jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
  - $HOME/.m2

matrix:
  fast_finish: true

install:
  - mvn compile -DskipTests -e

script:
  - mvn test

notifications:
  email: false
